### ISSUE TITLE
TODO - GLDebugDrawer::drawLine should draw using VBO

### ISSUE THREAD

**Issue by julapy** [NickHardeman/ofxBullet#15]
drawing all the debug lines in a VBO will greatly increase the performance.
suggested in this stackoverflow post,
http://stackoverflow.com/questions/14008295/how-to-implement-the-btidebugdraw-interface-of-bullet-in-opengl-4-0

**Comment by NickHardeman** [comment]
I finally implemented this ( in a mesh, not VBO ). Greatly improves performance. :)
