### ISSUE TITLE
XCode6 iOS8 compile issue of 0.8.4

### ISSUE THREAD

**Issue by TiborUdvari** [NickHardeman/ofxBullet#23]
I'm having trouble compiling
```
.../addons/ofxBullet/libs/bullet2.8.1/include/BulletMultiThreaded/GpuSoftBodySolvers/DX11/btSoftBodySolverVertexBuffer_DX11.h:22:10: 'windows.h' file not found`
```
The `windows.h` file is not found so I'm thinking the project configuration is off for *iOS in XCode6*. 

Here is what I'm doing : 

1. Copied `ofxBullet` into my `addons` folder
2. Used the `Project Generator` to create a new project 
3. Tried to compile this new project with `XCode6`

**Comment by NickHardeman** [comment]
Sorry for the delayed response. 
This post goes over how to use ofxBullet in from the current master branch with Xcode and the project generator. Please let me know if this fixes the issue for you.

**Comment by NickHardeman** [comment]
Removed pc specific files. Fixed by https://github.com/NickHardeman/ofxBullet/commit/8a2b3638bba71fe7824fc7a6529aa80eb8ac2741
