### ISSUE TITLE
Xcode 6.1 "EXC_BAD_ACCESS" with ofxBulletSimpleExample and others

### ISSUE THREAD

**Issue by wookee9** [NickHardeman/ofxBullet#26]
Hi there,
Firstly thank you for creating this project. It looks really awesome. 

Unfortunately I'm struggling to run any of the examples included with the library, with the exception of the 'emptyExample' project, which runs fine.

When running the SimpleExample, the project builds and runs, but straight away gives this error:

btMatrix3x3.h
Line 360
`Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)`

![screen shot 2014-11-26 at 15 55 35](https://cloud.githubusercontent.com/assets/841920/5204136/b8acf4a2-7584-11e4-83c2-1f8a32e00069.png)

Googling turns up this forum post...
http://www.bulletphysics.org/Bullet/phpBB3/viewtopic.php?f=9&t=8514

...But that's as far as I've got. I'm completely stumped by this. Any ideas?

Many thanks,

OF 0.8.4, Xcode 6.1, Mac OS 10.9.5

**Comment by rom-io** [comment]
nice, works a treat.

**Comment by wookee9** [comment]
+1 works great. Thanks!
