### ISSUE TITLE
Unknown Error 0x800700c1, Visual Studio 2015

### ISSUE THREAD

**Issue by tobiaszimmer** [NickHardeman/ofxBullet#40]
Hey,

I get the following error for each of the examples. Any idea what will help?
I also tried to create the Visual Studio files again with the project generator, but it remains the same..

![error](https://cloud.githubusercontent.com/assets/15525826/22614974/450ce3ee-ea8b-11e6-8400-48ef7afd4846.JPG)

**Comment by NickHardeman** [comment]
I don't have access to a Windows machine. Did you try building in 64 bit?

**Comment by tobiaszimmer** [comment]
Unfortunately it doesn't help, also changing to release mode produces the same error.

BUT;
I managed to start "SimpleExample", which had another error. (the function ofRotateDeg(180,1,0,0) does not exist, in → ofxBulletCone.cpp, in line 92. I exchanged it with ofRotateX(PI) (?))

Any idea why SimpleExample now works but the other examples do not? Even EmptyExample produces said error..

Thanks!

**Comment by tobiaszimmer** [comment]
Ok, if I create a completely new project with the project generator, include ofxBullet and then just exchange the src files of the examples it works.

Before I only tried to update the existing example folders with the project generator, which did not help..

**Comment by NickHardeman** [comment]
Hmm. Ok. I don't think I implemented anything to take into account the project generator. Maybe I have to structure the addon in a certain way for it to work properly with the pg?
Glad you were able to get it working. :)

**Comment by tobiaszimmer** [comment]
Hmm.. The project generator works, when creating a new project with ofxBullet. I think there is no need to implement anything special.
