### ISSUE TITLE
Not compiling OF098 Ubuntu 16.04

### ISSUE THREAD

**Issue by jucajuca** [NickHardeman/ofxBullet#43]
Hi I'm getting a bunch of errors while trying to compile some of the examples (EventExample in this case):

any idea about the cause?  

`In file included from /mnt/FILES/CODE/OF/OF_098/addons/ofxBullet/src/ofxBulletWorldRigid.h:14:0,
                 from /mnt/FILES/CODE/OF/OF_098/addons/ofxBullet/src/ofxBullet.h:11,
                 from /mnt/FILES/CODE/OF/OF_098/apps/myApps/EventsExample/src/ofApp.h:4,
                 from /mnt/FILES/CODE/OF/OF_098/apps/myApps/EventsExample/src/main.cpp:2:
/mnt/FILES/CODE/OF/OF_098/addons/ofxBullet/src/ofxBulletUtils.h:13:47: error: ‘glm’ has not been declared
 static btTransform ofGetBtTransformFromVec3f( glm::vec3 a_v ) {
                                               ^
/mnt/FILES/CODE/OF/OF_098/addons/ofxBullet/src/ofxBulletUtils.h:13:63: error: expected ‘,’ or ‘;’ before ‘{’ token
 static btTransform ofGetBtTransformFromVec3f( glm::vec3 a_v ) {
                                                               ^
/mnt/FILES/CODE/OF/OF_098/addons/ofxBullet/src/ofxBulletUtils.h:34:80: error: ‘glm’ has not been declared
 gidBody* ofGetBtRigidBodyFromCollisionShape(btCollisionShape* a_cs, glm::vec3 a
                                                                     ^
/mnt/FILES/CODE/OF/OF_098/addons/ofxBullet/src/ofxBulletUtils.h:34:90: error: expected ‘,’ or ‘...’ before ‘a_loc’
 fGetBtRigidBodyFromCollisionShape(btCollisionShape* a_cs, glm::vec3 a_loc, floa
                                                                     ^
/mnt/FILES/CODE/OF/OF_098/addons/ofxBullet/src/ofxBulletUtils.h: In function ‘btRigidBody* ofGetBtRigidBodyFromCollisionShape(btCollisionShape*, int)’:
/mnt/FILES/CODE/OF/OF_098/addons/ofxBullet/src/ofxBulletUtils.h:35:43: error: ‘a_loc’ was not declared in this scope
  btTransform tr=ofGetBtTransformFromVec3f(a_loc);`

**Comment by moebiussurfing** [comment]
the branch you are using is not for OF 0.9.8. should try in 0.10 or to use a previous state/branch

**Comment by moebiussurfing** [comment]
seems you are using the current 0.10 branch into 0.9.8
you can use a previous branch or to try in OF 0.10 or masterbranch
